export default function Head() {
  return (
    <>
      <title>Panaverse</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by Shahid" />
      <link rel="icon" href="/panaverse.svg" />
    </>
  );
}
